from __future__ import annotations

import csv
import json
from dataclasses import asdict
from pathlib import Path

import numpy as np

from .fitting import fitted_value
from .models import FitResult, GapRow


def write_csv(rows: list[GapRow], path: Path) -> None:
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(asdict(rows[0]).keys()))
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))


def write_json(result: FitResult, path: Path) -> None:
    path.write_text(json.dumps(asdict(result), ensure_ascii=False, indent=2), encoding="utf-8")


def write_formula_py(result: FitResult, path: Path) -> None:
    lines = [
        '# -*- coding: utf-8 -*-',
        '"""Standalone fitted Fourier function generated by lunar-gap-fit."""',
        '',
        'import math',
        '',
        f'MODE = {result.mode!r}',
        f'INPUT_DATE = {result.input_date!r}',
        f'SOLAR_MONTH = {result.solar_month!r}',
        f'SOLAR_DAY = {result.solar_day!r}',
        f'INPUT_LUNAR = {result.input_lunar!r}',
        f'MATCH_MODE = {result.match_mode!r}',
        f'SELECTED_PERIOD = {result.selected_period!r}',
        f'SELECTED_HARMONICS = {result.selected_harmonics!r}',
        f'Y0 = {result.start_year!r}',
        f'INTERCEPT = {result.intercept!r}',
        f'COS = {result.cos_coefficients!r}',
        f'SIN = {result.sin_coefficients!r}',
        '',
        'def gap_fit(year: float) -> float:',
        '    total = INTERCEPT',
        '    for k in range(1, SELECTED_HARMONICS + 1):',
        '        angle = 2 * math.pi * k * (year - Y0) / SELECTED_PERIOD',
        '        total += COS[k - 1] * math.cos(angle)',
        '        total += SIN[k - 1] * math.sin(angle)',
        '    return total',
        '',
        'def gap_fit_rounded(year: float) -> int:',
        '    return round(gap_fit(year))',
        '',
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def write_report(result: FitResult, rows: list[GapRow], path: Path) -> None:
    exact_years = [r.year for r in rows if r.gap_days == 0]
    lunar = result.input_lunar
    text = f"""# Lunar Gap Fourier Fit Report

Mode: `{result.mode}`

Input Gregorian date: `{result.input_date}`

Solar anchor: `{result.solar_month:02d}-{result.solar_day:02d}`

Lunar anchor: `{lunar.get('month')}-{lunar.get('day')}`

Match mode: `{result.match_mode}`

## Gap definition

`gap(Y) = matched lunar-anchor date - date(Y, solar_month, solar_day)`

Positive means lunar date is later. Negative means lunar date is earlier. Zero means exact coincidence.

## Range

`{result.start_year}` to `{result.end_year}`

Usable points: `{result.usable_points}`  
Skipped points: `{result.skipped_points}`

## Fourier model

```text
d(y) = c0 + Σ[k=1..{result.selected_harmonics}] {{
    a_k cos(2πk(y-{result.start_year})/{result.selected_period})
  + b_k sin(2πk(y-{result.start_year})/{result.selected_period})
}}
```

Selected period: `{result.selected_period:g}` years  
Selected harmonics: `{result.selected_harmonics}`  
Candidates evaluated: `{result.candidates_evaluated}`

## Fit quality

MAE: `{result.mae:.4f}` days  
RMSE: `{result.rmse:.4f}` days  
R²: `{result.r2:.6f}`  
BIC: `{result.bic:.4f}`

## Exact coincidence years

{', '.join(map(str, exact_years)) if exact_years else 'None in this range.'}
"""
    path.write_text(text, encoding="utf-8")


def write_plot(rows: list[GapRow], result: FitResult, path: Path) -> None:
    import matplotlib.pyplot as plt

    usable = [r for r in rows if r.gap_days is not None]
    years = np.array([r.year for r in usable], dtype=float)
    gaps = np.array([r.gap_days for r in usable], dtype=float)
    xfit = np.linspace(years.min(), years.max(), 2000)
    yfit = np.array([fitted_value(x, result) for x in xfit])
    plt.figure(figsize=(11, 5.8))
    plt.scatter(years, gaps, s=14, label="actual gap")
    plt.plot(xfit, yfit, linewidth=1.8, label=f"Fourier fit: P={result.selected_period:g}, N={result.selected_harmonics}")
    plt.axhline(0, linewidth=1)
    plt.xlabel("Year")
    plt.ylabel("Gap in days")
    plt.legend()
    plt.tight_layout()
    plt.savefig(path, dpi=180)
    plt.close()
